import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import Footer from "./components/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col">
        
        <div>
          <Link href="/">Home</Link> | <Link href="/about">About Me</Link> | <Link href="/contact">Contact Me</Link>
        </div>
        
        {children}
        
        <Footer />
      
      </body>
    </html>
  );
}
