//importing components and styles for the layout of the application
import "@/app/globals.css";
import type { Metadata } from "next";

import Footer from "./components/Footer";
import Navbar from "./components/Navbar";

//metadata for the application, including title and description
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//layout component/function that wraps around the entire application, providing a consistent structure and styling across all pages
//export default means that this function can be used by any other file
export default function RootLayout({
  //children is a special prop object that containt the content that will be rendered inside the layout component.
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
return (
    <html lang="en">
      <body className="min-h-screen">
       
        {/* main container for the application, with a white background */}
       <div className="min-h-screen grid grid-rows-[auto_1fr_auto]">
        
              
        <Navbar />
       
          <main>
            {children}
          </main>
        
        <Footer />
       </div>
              
      </body>
    </html>
  );
}
